apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "operator.fullname" . }}
  labels:
    {{- include "operator.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.controller.replicas | default 1 }}
  selector:
    matchLabels:
      app.kubernetes.io/role: controller
      {{- include "operator.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        app.kubernetes.io/role: controller
        {{- include "operator.labels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "operator.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ include "operator.appname" . }}
          image: "{{ .Values.image.listenerOperator.repository }}:{{ .Values.image.listenerOperator.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.listenerOperator.pullPolicy | default "IfNotPresent" }}
          args:
            - --leader-elect
            - --health-probe-bind-address={{ .Values.controller.healthProbe.bindAddress }}
            {{- if .Values.controller.metrics.enabled }}
            {{- $metricsPort := include "operator.metricsPort" .Values.controller.metrics }}
            - --metrics-bind-address=:{{ $metricsPort }}
            {{- if .Values.controller.metrics.secure }}
            - --metrics-secure=true
            {{- end }}
            {{- end }}
            - --zap-log-level={{ .Values.controller.logLevel | default 2 }}
          ports:
            {{- if .Values.controller.metrics.enabled }}
            {{- $metricsScheme := include "operator.metricsScheme" .Values.controller.metrics }}
            {{- $metricsPort := include "operator.metricsPort" .Values.controller.metrics }}
            - containerPort: {{ $metricsPort }}
              name: {{ $metricsScheme }}
              protocol: TCP
            {{- end }}
            {{- $healthPort := include "operator.healthProbePort" .Values.controller.healthProbe }}
            - containerPort: {{ $healthPort }}
              name: health
              protocol: TCP
          resources:
            {{- toYaml .Values.controller.resources | nindent 12 }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          livenessProbe:
            httpGet:
              path: /healthz
              port: {{ $healthPort }}
            initialDelaySeconds: 10
            timeoutSeconds: 3
            periodSeconds: 10
            failureThreshold: 5
          readinessProbe:
            httpGet:
              path: /healthz
              port: {{ $healthPort }}
            initialDelaySeconds: 5
            timeoutSeconds: 3
            periodSeconds: 5
            failureThreshold: 5
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
